# Generated by Django 4.1 on 2022-09-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evclidapp', '0002_indexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Главная страница'},
        ),
    ]
